### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by retrixe** [retrixe/ecthelion#23]
- [x] #25
- [x] Switch to `ky` for requests.
- [x] Show file names in page title.
- [x] Redirect parameter for `/login`
- [x] Multiple node support on the `/servers` page.
- [x] Blocking issue for Editor: https://github.com/mui/material-ui/pull/32783 (maybe downgrade to React 17?)
